image: docker.twofour.de/twofour-docker/docker:latest

stages:
    - build

build:
    stage: build
    tags:
        - docker-in-docker
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --pull --tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME} .
        - docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
